### PR TITLE
merge 

### PR DESCRIPTION
**Pull request by jami0003**

### CODE REVIEW

**Comment by chongguoliang** [comment]
Hi,

Please pull request again.

**Comment by jami0003** [comment]
Hi Guoliang,

I have requested for a pull request again from Tze Hui. Is the problem solved?

Thank you.

Regards
Jamie

**Comment by chongguoliang** [comment]
There is still 1 pull request in ISOMER.

**Comment by jami0003** [comment]
The pull request is “merge #52”right?

**Comment by chongguoliang** [comment]
Yes.

**Comment by JadynLCK** [comment]
Hi Jamie and Guo Liang,
Any action required on my end?

**Comment by jami0003** [comment]
Hi Jadyn and Guoliang,

I am waiting for my colleague to approve “merge #52”.

Thank you.

Regards
Jamie

**Comment by jami0003** [comment]
Hi Guo Liang,

Tze Hui is still unable to approve “merge 52”. I’m not sure why. Can you help to check if there is any other problem?

Thank you.

Regards
Jamie

From: Jamie LIM from.TP (IMDA)
Sent: Friday, 27 March 2020 9:08 AM
To: 'isomerpages/dlp' <reply@reply.github.com>; isomerpages/dlp <dlp@noreply.github.com>
Cc: State change <state_change@noreply.github.com>
Subject: RE: [isomerpages/dlp] merge (#51)

Hi Jadyn and Guoliang,

I am waiting for my colleague to approve “merge #52”.

Thank you.

Regards
Jamie

**Pull request closed without merging**
